name: portal
description: "Fkommerce is a complete F-commerce platform for shop owners,
  offering product sourcing, inventory management, customer management,
  accounting, and growth tools."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  beamer: ^2.0.0-dev.1
  connectivity_plus: ^6.0.3
  # crop_your_image: ^1.1.0
  crop_your_image:
    git:
      url: https://github.com/Noahbanderson/crop_your_image.git
      ref: main
  fast_cached_network_image: ^1.2.9
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^3.0.0-dev.3
  flutter_slidable: ^3.1.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_ui: ^1.0.14
  http: ^1.2.1
  image: ^4.2.0
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  # intl_phone_field: ^3.2.0
  intl_phone_field:
    git:
      url: https://github.com/sabikrahat/intl_phone_field.git
      ref: master
  logger: ^2.4.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.0
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icons/app-icon-1024x1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
  # command: dart run flutter_launcher_icons:main

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/icons/splash-icon-384x384.png"
  image_dark: "assets/icons/splash-icon-384x384.png"
  branding: "assets/icons/branding-512x80.png"
  branding_bottom_padding: 64
  # android_12:
  #   color: "#ffffff"
  #   color_dark: "#000000"
  #   image: "assets/icons/splash-icon-384x384.png"
  #   image_dark: "assets/icons/splash-icon-384x384.png"
  #   icon_background_color: "#ffffff"
  #   icon_background_color_dark: "#000000"
  #   branding: "assets/icons/branding-512x80.png"
  #   branding_bottom_padding: 64
  android: true
  ios: true
  web: true
  # command: dart run flutter_native_splash:create

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/svgs/
    - assets/types/

  fonts:
    - family: Urbanist
      fonts:
        # Extra Heavy Bold
        - asset: assets/fonts/Urbanist-ExtraHeavyBold.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-ExtraHeavyBoldItalic.ttf
          weight: 900
          style: italic
        # Extra Bold
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        # Bold
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-BoldItalic.ttf
          weight: 700
          style: italic
        # Semi Bold
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-SemiBoldItalic.ttf
          weight: 600
          style: italic
        # Medium
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        # Regular
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-RegularItalic.ttf
          weight: 400
          style: italic
        # Light
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        # Extra Light
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
        # Thin
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
